safe: true
pygments: true
lsi: false
permalink: /blog/:categories/:year/:month/:day/:title.html
paginate: 20
exclude: [README.md, Rakefile, lib, src, javascript/build.js, javascript/build.txt]

theme: normal